import TMI.DigitalLifeTwoAxisTick

/-!
# GINF-01: sampled hypergraph impulse

This module gives the rotating `G∞ · DL-04` reader scene a small formal kernel.
It separates three layers that the visualization must not merge:

* a carrier vertex type and a rendered screen-node type;
* an explicit projection from rendered nodes into the carrier;
* an admitted digital-life tick propagated along one visible graph edge.

The current reader uses `Fin 4000` for its rendered sample and
`Fin 1000000000000` for the declared trillion-vertex carrier.  Lean does not
enumerate a trillion vertices.  The two finite index types and their projection
are checked symbolically.

## Claim boundary

Visible connectedness is a property of the rendered sample only.  A proper
sample cannot supply a full-carrier coverage claim.  The admitted impulse
reuses the existing `DigitalLifeTwoAxisTick` receipt and therefore proves only
its explicit transition, time-touch, guard, and certificate obligations.  It
does not prove biological life, consciousness, quantum dynamics, a physical
time reversal, or empirical adequacy.  Rotation, zoom, and the 30/70 layout are
presentation data and do not advance the model state.
-/

namespace TMI.InterfaceFoundations.SampledHypergraphImpulse

open TMI.DigitalLifeTwoAxisTick

universe uCarrier uScreen uState uAction uIdentity uLab uInternal
  uQ uMemory uReflection uInput uModel uResult

/-- An explicit map from the nodes actually rendered on screen into an
underlying carrier.  Surjectivity is not assumed. -/
structure SampleProjection
    (CarrierVertex : Type uCarrier)
    (ScreenNode : Type uScreen) where
  map : ScreenNode -> CarrierVertex

/-- Every carrier vertex has at least one rendered representative. -/
def CoversCarrier
    {CarrierVertex : Type uCarrier}
    {ScreenNode : Type uScreen}
    (projection : SampleProjection CarrierVertex ScreenNode) : Prop :=
  forall vertex : CarrierVertex,
    exists node : ScreenNode, projection.map node = vertex

/-- A proper sample has an explicit carrier vertex omitted by every rendered
node.  This is stronger and more useful than merely naming the view a sample. -/
def ProperSample
    {CarrierVertex : Type uCarrier}
    {ScreenNode : Type uScreen}
    (projection : SampleProjection CarrierVertex ScreenNode) : Prop :=
  exists omitted : CarrierVertex,
    forall node : ScreenNode, projection.map node ≠ omitted

/-- An explicit omitted vertex rules out a full-carrier coverage claim. -/
theorem proper_sample_not_cover_carrier
    {CarrierVertex : Type uCarrier}
    {ScreenNode : Type uScreen}
    {projection : SampleProjection CarrierVertex ScreenNode}
    (proper : ProperSample projection) :
    Not (CoversCarrier projection) := by
  intro covers
  rcases proper with ⟨omitted, omittedFromScreen⟩
  rcases covers omitted with ⟨node, mapped⟩
  exact omittedFromScreen node mapped

/-- Reflexive/transitive reachability generated by visible binary edges. -/
inductive Reachable
    {ScreenNode : Type uScreen}
    (edge : ScreenNode -> ScreenNode -> Prop) :
    ScreenNode -> ScreenNode -> Prop where
  | refl (node : ScreenNode) : Reachable edge node node
  | step {source target : ScreenNode} :
      edge source target -> Reachable edge source target
  | trans {source middle target : ScreenNode} :
      Reachable edge source middle ->
      Reachable edge middle target ->
      Reachable edge source target

/-- The rendered object has binary edges, hyperedges, and a connectivity proof
for the screen-node type.  No carrier-level edge relation is smuggled in. -/
structure SampledHypergraph
    (CarrierVertex : Type uCarrier)
    (ScreenNode : Type uScreen)
    extends SampleProjection CarrierVertex ScreenNode where
  edge : ScreenNode -> ScreenNode -> Prop
  hyperedge : List ScreenNode -> Prop
  connected : forall source target : ScreenNode, Reachable edge source target

/-- A full-carrier claim must at minimum prove coverage.  Additional carrier
geometry would require further fields in a later module. -/
structure FullCarrierClaim
    {CarrierVertex : Type uCarrier}
    {ScreenNode : Type uScreen}
    (projection : SampleProjection CarrierVertex ScreenNode) : Prop where
  covers : CoversCarrier projection

/-- Connected pixels or screen nodes cannot upgrade a proper sample to a full
carrier statement: the required coverage field is contradictory. -/
theorem proper_sample_excludes_full_carrier_claim
    {CarrierVertex : Type uCarrier}
    {ScreenNode : Type uScreen}
    {projection : SampleProjection CarrierVertex ScreenNode}
    (proper : ProperSample projection) :
    Not (FullCarrierClaim projection) := by
  intro claim
  exact proper_sample_not_cover_carrier proper claim.covers

/-- The four public DL-04 readouts are projections of the already existing
living-model state.  They do not define a second transition function. -/
structure DL04Observation
    (State : Type uState)
    (Q : Type uQ)
    (Memory : Type uMemory)
    (Reflection : Type uReflection)
    (Input : Type uInput) where
  q : State -> Q
  memory : State -> Memory
  reflection : State -> Reflection
  input : State -> Input
  certificate : State -> Nat
  guard : State -> Prop

/-- Typed DL-04 state surface matching the public reader readouts.  The exact
numeric transition remains the `applyAction` field of the reused tick contract,
so this structure does not introduce a competing dynamics. -/
structure DL04State
    (Q : Type uQ)
    (Memory : Type uMemory)
    (Reflection : Type uReflection)
    (Input : Type uInput) where
  q : Q
  memory : Memory
  reflection : Reflection
  input : Input
  certificate : Nat
  guard : Bool

/-- Canonical observation of a typed DL-04 state. -/
def DL04State.observation
    {Q : Type uQ}
    {Memory : Type uMemory}
    {Reflection : Type uReflection}
    {Input : Type uInput} :
    DL04Observation
      (DL04State Q Memory Reflection Input) Q Memory Reflection Input where
  q := DL04State.q
  memory := DL04State.memory
  reflection := DL04State.reflection
  input := DL04State.input
  certificate := DL04State.certificate
  guard := fun state => state.guard = true

/-- One guarded, admitted tick travels along a visible edge.  Its transition
certificate is the existing `TickReceipt`, not an unchecked animation event. -/
structure SampledImpulseStep
    {CarrierVertex : Type uCarrier}
    {ScreenNode : Type uScreen}
    {State : Type uState}
    {Action : Type uAction}
    {Identity : Type uIdentity}
    {TLab : Type uLab}
    {TInternal : Type uInternal}
    {Q : Type uQ}
    {Memory : Type uMemory}
    {Reflection : Type uReflection}
    {Input : Type uInput}
    (graph : SampledHypergraph CarrierVertex ScreenNode)
    (contract : TickContract State Action Identity TLab TInternal)
    (observation : DL04Observation State Q Memory Reflection Input) where
  source : ScreenNode
  target : ScreenNode
  followsVisibleEdge : graph.edge source target
  receipt : TickReceipt contract
  certificateBeforeMatches :
    observation.certificate receipt.event.before =
      contract.certificate receipt.event.before
  certificateAfterMatches :
    observation.certificate receipt.event.after =
      contract.certificate receipt.event.after
  guardBefore : observation.guard receipt.event.before
  guardAfter : observation.guard receipt.event.after

/-- The impulse uses exactly the transition function declared by the reused
digital-life tick contract. -/
theorem sampled_impulse_applies_declared_transition
    {CarrierVertex : Type uCarrier}
    {ScreenNode : Type uScreen}
    {State : Type uState}
    {Action : Type uAction}
    {Identity : Type uIdentity}
    {TLab : Type uLab}
    {TInternal : Type uInternal}
    {Q : Type uQ}
    {Memory : Type uMemory}
    {Reflection : Type uReflection}
    {Input : Type uInput}
    {graph : SampledHypergraph CarrierVertex ScreenNode}
    {contract : TickContract State Action Identity TLab TInternal}
    {observation : DL04Observation State Q Memory Reflection Input}
    (step : SampledImpulseStep graph contract observation) :
    step.receipt.event.after =
      contract.applyAction
        step.receipt.event.before step.receipt.event.action :=
  step.receipt.certified.applied

/-- Every admitted visible impulse extends the reused certificate by one. -/
theorem sampled_impulse_extends_certificate
    {CarrierVertex : Type uCarrier}
    {ScreenNode : Type uScreen}
    {State : Type uState}
    {Action : Type uAction}
    {Identity : Type uIdentity}
    {TLab : Type uLab}
    {TInternal : Type uInternal}
    {Q : Type uQ}
    {Memory : Type uMemory}
    {Reflection : Type uReflection}
    {Input : Type uInput}
    {graph : SampledHypergraph CarrierVertex ScreenNode}
    {contract : TickContract State Action Identity TLab TInternal}
    {observation : DL04Observation State Q Memory Reflection Input}
    (step : SampledImpulseStep graph contract observation) :
    contract.certificate step.receipt.event.after =
      contract.certificate step.receipt.event.before + 1 :=
  admitted_extends_certificate step.receipt.certified

/-- Certificate growth is monotone along every admitted visible impulse. -/
theorem sampled_impulse_certificate_monotone
    {CarrierVertex : Type uCarrier}
    {ScreenNode : Type uScreen}
    {State : Type uState}
    {Action : Type uAction}
    {Identity : Type uIdentity}
    {TLab : Type uLab}
    {TInternal : Type uInternal}
    {Q : Type uQ}
    {Memory : Type uMemory}
    {Reflection : Type uReflection}
    {Input : Type uInput}
    {graph : SampledHypergraph CarrierVertex ScreenNode}
    {contract : TickContract State Action Identity TLab TInternal}
    {observation : DL04Observation State Q Memory Reflection Input}
    (step : SampledImpulseStep graph contract observation) :
    contract.certificate step.receipt.event.before <=
      contract.certificate step.receipt.event.after := by
  rw [sampled_impulse_extends_certificate step]
  exact Nat.le_succ _

/-- The public DL-04 certificate readout agrees with the reused tick contract
and is therefore monotone as well. -/
theorem sampled_impulse_observed_certificate_monotone
    {CarrierVertex : Type uCarrier}
    {ScreenNode : Type uScreen}
    {State : Type uState}
    {Action : Type uAction}
    {Identity : Type uIdentity}
    {TLab : Type uLab}
    {TInternal : Type uInternal}
    {Q : Type uQ}
    {Memory : Type uMemory}
    {Reflection : Type uReflection}
    {Input : Type uInput}
    {graph : SampledHypergraph CarrierVertex ScreenNode}
    {contract : TickContract State Action Identity TLab TInternal}
    {observation : DL04Observation State Q Memory Reflection Input}
    (step : SampledImpulseStep graph contract observation) :
    observation.certificate step.receipt.event.before <=
      observation.certificate step.receipt.event.after := by
  rw [step.certificateBeforeMatches, step.certificateAfterMatches]
  exact sampled_impulse_certificate_monotone step

/-- The visible impulse inherits the existing two-axis-time witness. -/
theorem sampled_impulse_has_time_touch
    {CarrierVertex : Type uCarrier}
    {ScreenNode : Type uScreen}
    {State : Type uState}
    {Action : Type uAction}
    {Identity : Type uIdentity}
    {TLab : Type uLab}
    {TInternal : Type uInternal}
    {Q : Type uQ}
    {Memory : Type uMemory}
    {Reflection : Type uReflection}
    {Input : Type uInput}
    {graph : SampledHypergraph CarrierVertex ScreenNode}
    {contract : TickContract State Action Identity TLab TInternal}
    {observation : DL04Observation State Q Memory Reflection Input}
    (step : SampledImpulseStep graph contract observation) :
    EnvelopeTimeTouch contract step.receipt.event :=
  receipt_has_timeTouch step.receipt

/-- Presentation parameters used by the reader.  Integer angle units are a UI
encoding only and have no physical or geometric interpretation here. -/
structure ViewFrame where
  scalePercent : Nat
  yawUnits : Int
  pitchUnits : Int
  leftWeight : Nat
  rightWeight : Nat

/-- A model paired with presentation data. -/
structure Presented (Model : Type uModel) where
  model : Model
  view : ViewFrame

/-- Change only the view frame. -/
def reframe
    {Model : Type uModel}
    (presented : Presented Model)
    (view : ViewFrame) : Presented Model :=
  { model := presented.model, view := view }

/-- Rotation, zoom, and layout changes leave the model value untouched. -/
@[simp] theorem reframe_preserves_model
    {Model : Type uModel}
    (presented : Presented Model)
    (view : ViewFrame) :
    (reframe presented view).model = presented.model :=
  rfl

/-- Every observation of the model is invariant under a pure reframe. -/
theorem reframe_preserves_observation
    {Model : Type uModel}
    {Result : Type uResult}
    (observe : Model -> Result)
    (presented : Presented Model)
    (view : ViewFrame) :
    observe (reframe presented view).model = observe presented.model :=
  rfl

/-- Public reader constants.  They are symbolic finite types, not enumerated
lists allocated by the Lean checker or the browser. -/
def renderedVertexCount : Nat := 4000
def trillionVertexCount : Nat := 1000000000000

abbrev RenderedNode := Fin renderedVertexCount
abbrev TrillionCarrierVertex := Fin trillionVertexCount

/-- The rendered nodes occupy the first 4000 indices of the trillion-index
carrier. -/
def renderedToTrillion :
    SampleProjection TrillionCarrierVertex RenderedNode where
  map := fun node =>
    ⟨node.val, Nat.lt_trans node.isLt (by decide : renderedVertexCount < trillionVertexCount)⟩

/-- The first carrier index beyond the rendered sample. -/
def firstOmittedTrillionVertex : TrillionCarrierVertex :=
  ⟨renderedVertexCount, by decide⟩

/-- The 4000-node projection is formally proper: carrier index 4000 is not a
rendered node. -/
theorem rendered_projection_is_proper :
    ProperSample renderedToTrillion := by
  refine ⟨firstOmittedTrillionVertex, ?_⟩
  intro node mapped
  have sameValue : node.val = renderedVertexCount :=
    congrArg Fin.val mapped
  exact (Nat.ne_of_lt node.isLt) sameValue

/-- Therefore the rendered sample cannot be presented as a full coverage of
the trillion-index carrier. -/
theorem rendered_sample_does_not_cover_trillion :
    Not (CoversCarrier renderedToTrillion) :=
  proper_sample_not_cover_carrier rendered_projection_is_proper

end TMI.InterfaceFoundations.SampledHypergraphImpulse
