import TMI.InterfaceMathematics.ContextualInterface

open TMI.InterfaceMathematics.ContextualInterface

#print axioms has_global_section_iff_nonempty_witness
#print axioms global_section_gives_pairwise_compatible
#print axioms erasing_the_context_index_forces_a_false_identification
#print axioms plan_family_has_contextual_obstruction
#print axioms pairwise_compatibility_does_not_imply_global_gluing
#print axioms nondisturbing_probe_reveals_preexisting_obstruction
#print axioms obstruction_revealed_by_nondisturbing_probe_was_preexisting
#print axioms disturbing_probe_can_create_a_revealed_obstruction
#print axioms creating_probe_has_no_preexisting_obstruction
#print axioms creating_probe_is_not_nondisturbing
#print axioms classical_mixture_kernel_is_diagonal
#print axioms classical_context_has_no_coherence_witness
#print axioms pure_context_has_coherence_from_two_supported_indices
#print axioms unknown_classical_context_is_not_quantum_coherence
