import AISOValidationKernel

open AISOValidationKernel

#print axioms execute_some_iff_triple_closure
#print axioms execute_none_iff_silence
#print axioms left_rejection_means_silence
#print axioms right_rejection_means_silence
#print axioms incompatibility_means_silence
#print axioms execution_never_substitutes_act
