import PoetryOfMathematics

open TMI.PoetryOfMathematics

#print axioms shadow_membership_iff
#print axioms occlusion_witness_is_strictly_bounded
#print axioms obstacle_behind_receiver_is_not_occluding
#print axioms visibility_weight_between_zero_and_kernel
#print axioms irradiance_bounds
#print axioms soft_shadow_identity
#print axioms sigma_between_zero_and_one
#print axioms radiometric_sigma_between_zero_and_one
#print axioms boundary_subset_projected_tangencies
#print axioms boundary_eq_projected_visible_tangencies
#print axioms reality_trace_candidate_requires_check
#print axioms unverified_beauty_is_not_reality_trace
#print axioms poetic_reading_presupposes_magic
#print axioms poetic_reading_requires_readability
#print axioms dRadius_rotateBy_zero
#print axioms dTheta_rotateBy
#print axioms rotateBy_preserves_status
#print axioms radial_approach_requires_independent_verification
#print axioms fact_promotion_requires_independent_verification
#print axioms no_verification_blocks_radial_approach
#print axioms no_verification_blocks_fact_promotion
#print axioms interpretation_changes_angle_not_fact_status
#print axioms physical_hypothesis_geometry_is_not_a_kernel_theorem
#print axioms metaphysical_canon_is_not_a_kernel_theorem
#print axioms other_worlds_claim_is_outside_the_theory
